"""Type stubs for the `lua` extension module (lua-python-bridge)."""
from typing import Any, Callable, Iterable, Iterator, Mapping, MutableSequence, overload

__version__: str
LUA_VERSION: str

class LuaError(Exception):
    """An error raised by Lua code.

    Instances created by the bridge carry the original Lua error value (converted to Python) in
    ``value`` and the Lua stack traceback in ``traceback``.
    """
    value: Any
    traceback: str | None

class LuaObject:
    """A Lua table, function, userdata or thread.

    Attribute access reads table fields; missing fields are ``None``, except dunder names, which
    raise ``AttributeError``. ``keys()``, ``values()`` and ``items()`` are used when the table has
    no field of that name. Calling passes positional arguments; keyword arguments arrive in Lua as
    one trailing table. Equality and hashing follow Lua's raw equality.
    """
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: "LuaObject") -> bool: ...
    def __le__(self, other: "LuaObject") -> bool: ...
    def keys(self) -> list[Any]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[Any, Any]]: ...

class LuaSequence(MutableSequence[Any]):
    """A 0-based list view of a Lua array: ``lua.seq(t)[0]`` is ``t[1]``."""
    @overload
    def __getitem__(self, index: int) -> Any: ...
    @overload
    def __getitem__(self, index: slice) -> list[Any]: ...
    def __setitem__(self, index: int, value: Any) -> None: ...  # type: ignore[override]
    def __delitem__(self, index: int) -> None: ...  # type: ignore[override]
    def __len__(self) -> int: ...
    def insert(self, index: int, value: Any) -> None: ...
    def append(self, value: Any) -> None: ...
    def pop(self, index: int = -1) -> Any: ...
    def extend(self, values: Iterable[Any]) -> None: ...
    def clear(self) -> None: ...

def execute(code: str | bytes) -> Any:
    """Run a Lua chunk; returns None, its single result, or a tuple of results."""
def eval(expr: str | bytes) -> Any:
    """Evaluate a Lua expression (or a comma-separated list of them)."""
def globals() -> LuaObject:
    """The Lua globals table."""
def require(name: str) -> Any:
    """Call Lua's ``require``."""
def table(*items: Any, **fields: Any) -> LuaObject:
    """A new Lua table ``{items..., field=value...}``."""
def table_from(obj: Mapping[Any, Any] | Iterable[Any]) -> LuaObject:
    """A new Lua table from a mapping (keys kept) or an iterable (1-based array)."""
def seq(t: LuaObject) -> LuaSequence:
    """A 0-based list view of a Lua array."""
def tablecall(f: LuaObject) -> Callable[..., Any]:
    """``tablecall(f)(*args, **kwargs)`` calls the Lua function ``f`` with one argument table
    ``{args..., name=value...}``."""
