/* Generated by tools/gen_pyapi.py from the CPython 3.10 limited API headers. Do not edit. */
/* Included after <Python.h> in the Lua module build: CPython data symbols resolve
   through pointers that pyloader.c fills when it loads libpython. */
#ifndef LPB_PYAPI_H
#define LPB_PYAPI_H

extern PyObject * *lpb_data_PyExc_AttributeError;
#define PyExc_AttributeError (*lpb_data_PyExc_AttributeError)
extern PyObject * *lpb_data_PyExc_IndexError;
#define PyExc_IndexError (*lpb_data_PyExc_IndexError)
extern PyObject * *lpb_data_PyExc_KeyError;
#define PyExc_KeyError (*lpb_data_PyExc_KeyError)
extern PyObject * *lpb_data_PyExc_LookupError;
#define PyExc_LookupError (*lpb_data_PyExc_LookupError)
extern PyObject * *lpb_data_PyExc_MemoryError;
#define PyExc_MemoryError (*lpb_data_PyExc_MemoryError)
extern PyObject * *lpb_data_PyExc_RuntimeError;
#define PyExc_RuntimeError (*lpb_data_PyExc_RuntimeError)
extern PyObject * *lpb_data_PyExc_TypeError;
#define PyExc_TypeError (*lpb_data_PyExc_TypeError)
extern PyObject * *lpb_data_PyExc_UnicodeDecodeError;
#define PyExc_UnicodeDecodeError (*lpb_data_PyExc_UnicodeDecodeError)
extern PyObject * *lpb_data_PyExc_UnicodeEncodeError;
#define PyExc_UnicodeEncodeError (*lpb_data_PyExc_UnicodeEncodeError)
extern PyObject * *lpb_data_PyExc_ValueError;
#define PyExc_ValueError (*lpb_data_PyExc_ValueError)
extern PyTypeObject *lpb_data_PyFloat_Type;
#define PyFloat_Type (*lpb_data_PyFloat_Type)
extern PyTypeObject *lpb_data_PyModule_Type;
#define PyModule_Type (*lpb_data_PyModule_Type)
extern PyTypeObject *lpb_data_PySlice_Type;
#define PySlice_Type (*lpb_data_PySlice_Type)
extern struct _longobject *lpb_data__Py_FalseStruct;
#define _Py_FalseStruct (*lpb_data__Py_FalseStruct)
extern PyObject *lpb_data__Py_NoneStruct;
#define _Py_NoneStruct (*lpb_data__Py_NoneStruct)
extern PyObject *lpb_data__Py_NotImplementedStruct;
#define _Py_NotImplementedStruct (*lpb_data__Py_NotImplementedStruct)
extern struct _longobject *lpb_data__Py_TrueStruct;
#define _Py_TrueStruct (*lpb_data__Py_TrueStruct)

#endif
